# Generated by Django 4.0.3 on 2022-03-25 03:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='full_name'),
        ),
    ]
